### ISSUE TITLE
Hyperledger Fabric query.js ; Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]

### ISSUE THREAD

**Issue by infiduk** [walton-blockchain-institute-2nd-term/hyperledger#1]
![Hyperledger_TimeOutError_(start sh에서 timeout 시간을 늘려준다 )](https://user-images.githubusercontent.com/48206157/61694155-e1a05d80-ad6b-11e9-835b-1d64c5436e24.PNG)
```
[Channel.js]: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
[Network]: _initializeInternalChannel: Unable to initialize channel. Attempted to contact 1 Peers.
```

`./start.sh` 해서 docker 실행시키고 `node query.js` 했을 때 발생하는 에러

**Comment by infiduk** [comment]
`./start.sh` 안의 `FABRIC_START_TIMEOUT` 값을 늘려주면 됩니다..
```
export FABRIC_START_TIMEOUT = 30
```
컴퓨터가 느려서 실행도 느린데 타임아웃을 작게 잡아둬서 채널이 생성되지 않아? 발생하는 오류..

**Comment by losnah-think** [comment]
에러해결방안 알려주셔서 감사해요!
