### ISSUE TITLE
Hyperledger Fabric startFabric.sh ; line 46 ./docker-compose.yml 이 어떻게 실행되는건가요?

### ISSUE THREAD

**Issue by infiduk** [walton-blockchain-institute-2nd-term/hyperledger#7]
```
docker-compose -f ./docker-compose.yml up -d cli
```
경로에 `docker-compose.yml` 파일이 없어요..

**Comment by ch-4ml** [comment]
저거 -f 옵션이 실행했던 곳에서 계속 실행하고.. 뭐 그런거였던 것 같은데 찾

**Comment by infiduk** [comment]
[팀 개발 속도 향상을 위한 3가지 Docker compose 기능들](http://www.hanbit.co.kr/channel/category/category_view.html?cms_code=CMS4147169696) 에 관련 설명이 나와있습니다!

`-f` 옵션이란 기본 `docker-compose.yml` 파일을 무시하고 사용자가 명시한 단 하나의 파일만 사용하도록 합니다.
저 명령어에서는 사용자가 임의의 `docker-compose.yml` 이라는 파일을 명시했고 사용한다는 거겠죠?
즉, 경로에 파일이 없어도 실행이 된다고 보시면 될 것 같네요.. (명시된 파일은 하나밖에 없으니까요 ㅎㅎ)

추가로 [docker-compose 사용법 및 예제](https://pages.wiserain.com/articles/cheatsheet-docker-compose/) docker-compose에 대한 옵션 설명이 나와있는 사이트입니다.
`up` 옵션은 자동으로 업데이트가 되도록 하는 것이고, `-d` 옵션은 백그라운드로 보내라는 뜻이라고 하네요 굿굿~
